apiVersion: apps/v1
kind: Deployment
metadata:
  name: mavenwebapp
spec:
  selector:
    matchLabels:
      app: mavenwebapp
  template:
    metadata:
      labels:
        app: mavenwebapp
    spec:
      containers:
      - name: mavenwebapp
        image: asad059/maven-app:2
        ports:
        - containerPort: 8080
