apiVersion: apps/v1
kind: Deployment
metadata:
  name: mavenapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mavenwebapp
  template:
    metadata:
      labels:
        app: mavenwebapp
    spec:
      containers:
      - name: mavenwebapp
        image: asad059/maven-app:2
        ports:
        - containerPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mavenwebappingress
  namespace: myapp
spec:
  ingressClassName: nginx
  rules:
  - host: mavenwebapp.asad.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: mavenwebappsvc
            port:
              number: 8080
